Чтобы создать собственный тип ошибки, достаточно реализовать метод `Error()`.

```go
type error interface {
    Error() string
}
```

Создадим ошибку, которая описывает проблему поиска `substr` в строке `src`:

```go
type lookupError struct {
    src    string
    substr string
}

func (e lookupError) Error() string {
    return fmt.Sprintf("'%s' not found in '%s'", e.substr, e.src)
}
```

Напишем функцию `indexOf()`, которая возвращает индекс вхождения подстроки `substr` в строку `src`. Если вхождения нет, возвращает ошибку типа `lookupError`:

```go
func indexOf(src string, substr string) (int, error) {
    idx := strings.Index(src, substr)
    if idx == -1 {
        // Создаем и возвращаем ошибку типа `lookupError`.
        return -1, lookupError{src, substr}
    }
    return idx, nil
}
```

Проверим работу `indexOf()` для разных подстрок.

```go
src := "go is awesome"
for _, substr := range []string{"go", "js"} {
    if res, err := indexOf(src, substr); err != nil {
        fmt.Printf("indexOf(%#v, %#v) failed: %v\n", src, substr, err)
    } else {
        fmt.Printf("indexOf(%#v, %#v) = %v\n", src, substr, res)
    }
}
// indexOf("go is awesome", "go") = 0
// indexOf("go is awesome", "js") failed: 'js' not found in 'go is awesome'
```

Поскольку `indexOf()` возвращает общий тип `error`, чтобы получить доступ к конкретному объекту ошибки, придется использовать приведение типа:

```go
_, err := indexOf(src, "js")
if err, ok := err.(lookupError); ok {
    fmt.Println("err.src:", err.src)
    fmt.Println("err.substr:", err.substr)
}
// err.src: go is awesome
// err.substr: js
```


Иногда в ошибке, кроме текста, нужно передать дополнительную информацию. Разберём пример, в котором вместе с текстом ошибки будем возвращать время её возникновения:

```go
import (
    "fmt"
    "time"
)
// Создадим собственный тип, который удовлетворяет интерфейсу error
// TimeError — тип для хранения времени и текста ошибки.
type TimeError struct {
    Time time.Time
    Text string
}

// Error добавляет поддержку интерфейса error для типа TimeError.
func (te TimeError) Error() string {
    return fmt.Sprintf("%v: %v", te.Time.Format(`2006/01/02 15:04:05`), te.Text)
}

// NewTimeError возвращает переменную типа TimeError c текущим временем.
func NewTimeError(text string) TimeError {
    return TimeError{
        Time: time.Now(),
        Text: text,
    }
}

func testFunc(i int) error {
    // несмотря на то что NewTimeError возвращает тип TimeError,
    // у testFunc тип возвращаемого значения равен error
    if i == 0 {
        return NewTimeError(`параметр в testFunc равен 0`)
    }
    return nil
}

func main() {
    if err := testFunc(0); err != nil {
        fmt.Println(err)
    }
} 
```

Получим примерно следующее:

```
2021/05/28 11:33:00: Параметр в testFunc равен 0 
```

Если ошибкой может выступать переменная любого интерфейсного типа `error`, значит, можно использовать операцию **утверждения типа** (**type assertion**) для конвертации ошибки в конкретный базовый тип. Про интерфейсы вы узнаете в следующем спринте.

```go
if err := testFunc(0); err != nil {
    if v, ok := err.(TimeError); ok {
        fmt.Println(v.Time, v.Text)
    } else {
        fmt.Println(err)
    }
} 
```

Если ошибки могут быть разных типов, логично использовать конструкцию выбора типа:

```go
if err := testFunc(0); err != nil {
    switch v := err.(type) {
    case TimeError:
        fmt.Println(v.Time, v.Text)
    case *os.PathError:
        fmt.Println(v.Err)
    default:
        fmt.Println(err)
    }
} 
```

Но лучше применить функцию `As` пакета `errors`, так как она, в отличие от `type assertion`, работает с «обёрнутыми» ошибками, которые разберём ниже. `As` находит первую в цепочке ошибку `err`, устанавливает тип, равным этому значению ошибки, и возвращает `true`.

```go
if err := testFunc(0); err != nil {
    var te TimeError
    if ok := errors.As(err, &te); ok { //  Сравниваем полученную и контрольную ошибки. Сравнение идёт по типу ошибки.
        fmt.Println(te.Time, te.Text)
    } else {
        fmt.Println(err)
    }
} 
```

Возвращение ошибки не всегда означает, что ситуация критическая. Ошибка может сообщать о статусе или состоянии какого-то действия или ресурса. Например, при проверке наличия файла нужно дополнительно проверить полученную ошибку функцией `os.IsNotExist`. Другой пример — чтение из источника должно продолжаться до получения ошибки `io.EOF`, которая сигнализирует о том, что все данные прочитаны.

```go
func main() {
    if data, err := ReadTextFile(`myconfig.yaml`); err != nil {
        if os.IsNotExist(errors.Unwrap(err)) {
            fmt.Println(`Файл не существует!`)
        }
    } else {
        fmt.Println(data)
    }
} 
```

В данном примере можно использовать функцию `Is(err, target error) bool` из пакета `errors`, которая определяет, содержит ли цепочка ошибок конкретную ошибку.

```go
func main() {
    data, err := ReadTextFile("myconfig.yaml")
    if errors.Is(err, os.ErrNotExist) {
        fmt.Println("Файл не найден")
        return
    }
    fmt.Println(data)
} 
```




[[Ошибки]]