Есть функция, которая обычно отрабатывает за 10 мс, но в 20% случаев занимает 200 мс:

```go
func work() int {
    if rand.Intn(10) < 8 {
        time.Sleep(10 * time.Millisecond)
    } else {
        time.Sleep(200 * time.Millisecond)
    }
    return 42
}
```

Мы в принципе не хотим ждать дольше, скажем, 50 мс. Поэтому установим _таймаут_ (timeout) — максимальное время, в течение которого готовы ждать ответ. Если операция не уложилась в таймаут, будем считать это ошибкой.

Сделаем обертку, которая выполняет переданную функцию с указанным таймаутом, и будем вызывать ее вот так:

```go
func withTimeout(fn func() int, timeout time.Duration) (int, error) {
    // ...
}

func main() {
    for i := 0; i < 10; i++ {
        start := time.Now()
        timeout := 50 * time.Millisecond
        if answer, err := withTimeout(work, timeout); err != nil {
            fmt.Printf("Took longer than %v. Error: %v\n", time.Since(start), err)
        } else {
            fmt.Printf("Took %v. Result: %v\n", time.Since(start), answer)
        }
    }
}
```

```bash
Took 10ms. Result: 42
Took 10ms. Result: 42
Took 10ms. Result: 42
Took longer than 50ms. Error: timeout
Took 10ms. Result: 42
Took longer than 50ms. Error: timeout
Took 10ms. Result: 42
Took 10ms. Result: 42
Took 10ms. Result: 42
Took 10ms. Result: 42
```

Идея работы `withTimeout()` следующая:

-   Запускаем переданную `fn()` в отдельной горутине.
-   Ждем в течение `timeout` времени.
-   Если `fn()` вернула ответ — возвращаем его.
-   Если не успела — возвращаем ошибку.

Вот как можно это реализовать:

```go
func withTimeout(fn func() int, timeout time.Duration) (int, error) {
   var result int

	done := make(chan struct{})
	go func() {
		result = fn()
		done <- struct{}{}
	}()

	select {
	case <-done:
		close(done)
		return result, nil
	case <-time.After(timeout):
		return 0, errors.New("timeout")
	}
}
```

Здесь все знакомо, кроме `[time.After()](https://pkg.go.dev/time#After)`. Эта библиотечная функция возвращает канал, который изначально пуст, а через `timeout` времени отправляет в него значение. Благодаря этому `select` выберет нужный вариант:

-   ветку `<-done`, если `fn()` успела до таймаута (вернет ответ);
-   ветку `<-time.After()`, если не успела (вернет ошибку).

[песочница](https://go.dev/play/p/3u8okYtkWFp)

# Контекст таймаут

Настоящая сила контекста в том, что его можно использовать как для ручной отмены, так и для отмены по таймауту. Следите за руками:

```go
// выполняет функцию fn с учетом контекста ctx
func execute(ctx context.Context, fn func() int) (int, error) {
    // код не меняется
}

func main() {
    // ...

    // работает в течение 100 мс
    work := func() int {
        // ...
    }

    // возвращает случайный агрумент из переданных
    randomChoice := func(arg ...int) int {
        i := rand.Intn(len(arg))
        return arg[i]
    }

    // случайный таймаут - 50 мс либо 150 мс
    timeout := time.Duration(randomChoice(50, 150)) * time.Millisecond
    ctx, cancel := context.WithTimeout(context.Background(), timeout)    // (1)
    defer cancel()

    res, err := execute(ctx, work)
    fmt.Println(res, err)
}
```

Функция `execute()` вообще не изменилась, а в `main()` вместо `context.WithCancel()` теперь `context.WithTimeout()` ➊. Этого достаточно, чтобы `execute()` теперь отваливалась по таймауту в половине случаев (ошибка `context.DeadlineExceeded`):

```no-highlight
work done
42 <nil>

0 context deadline exceeded

0 context deadline exceeded

work done
42 <nil>
```

Благодаря контексту, функции `execute()` больше не нужно знать, чем вызвана отмена — ручным действием или таймаутом. Все, что от нее требуется — слушать сигнал отмены на канале `ctx.Done()`.

Удобно!

[песочница](https://go.dev/play/p/WBdOX8LvBQT) [[Родительский и дочерний таймауты]] 